### ISSUE TITLE
Error when running demo.py

### ISSUE THREAD

**Issue by patrickbusser** [Zielon/MICA#37]
I cloned the project, ran the install.sh file without errors, then I activated the environment and when I tried to run demo.py, I got:

`(MICA) patrick@Alien:~/MICA$ python demo.py
2022-11-17 23:47:03.894 | INFO     | models.flame:__init__:54 - [FLAME] creating the FLAME Decoder

Traceback (most recent call last):
  File "demo.py", line 157, in <module>
    main(cfg, args)
  File "demo.py", line 105, in main
    mica = util.find_model_using_name(model_dir='micalib.models', model_name=cfg.model.name)(cfg, device)
  File "/home/patrick/MICA/micalib/models/mica.py", line 37, in __init__
    self.initialize()
  File "/home/patrick/MICA/micalib/base_model.py", line 45, in initialize
    self.create_flame(self.cfg.model)
  File "/home/patrick/MICA/micalib/base_model.py", line 53, in create_flame
    self.flame = FLAME(model_cfg).to(self.device)
  File "/home/patrick/anaconda3/envs/MICA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 907, in to
    return self._apply(convert)
  File "/home/patrick/anaconda3/envs/MICA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 601, in _apply
    param_applied = fn(param)
  File "/home/patrick/anaconda3/envs/MICA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 905, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/patrick/anaconda3/envs/MICA/lib/python3.8/site-packages/torch/cuda/__init__.py", line 216, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero.
`

Any idea how to solve this?

**Comment by thornade05** [comment]
Hi,
Thank for your help, env conda installed.
But when i launch demo.py i have this issue:

Traceback (most recent call last):
  File "demo.py", line 28, in <module>
    from insightface.app import FaceAnalysis
  File "/home/titof/anaconda3/envs/MICA/lib/python3.8/site-packages/insightface/__init__.py", line 18, in <module>
    from . import app
  File "/home/titof/anaconda3/envs/MICA/lib/python3.8/site-packages/insightface/app/__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "/home/titof/anaconda3/envs/MICA/lib/python3.8/site-packages/insightface/app/mask_renderer.py", line 8, in <module>
    from ..thirdparty import face3d
  File "/home/titof/anaconda3/envs/MICA/lib/python3.8/site-packages/insightface/thirdparty/face3d/__init__.py", line 3, in <module>
    from . import mesh
  File "/home/titof/anaconda3/envs/MICA/lib/python3.8/site-packages/insightface/thirdparty/face3d/mesh/__init__.py", line 9, in <module>
    from .cython import mesh_core_cython
  File "insightface/thirdparty/face3d/mesh/cython/mesh_core_cython.pyx", line 1, in init insightface.thirdparty.face3d.mesh.cython.mesh_core_cython
**ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject**

Could you help me, thk

**Comment by Zielon** [comment]
I would try to reinstall the env. I updated the conda file.
