### ISSUE TITLE
error demo.py - ValueError: numpy.ndarray

### ISSUE THREAD

**Issue by thornade05** [Zielon/MICA#38]
Hi,
Thank for your help, env conda installed.
But when i launch demo.py i have this issue:

Traceback (most recent call last):
  File "demo.py", line 28, in <module>
    from insightface.app import FaceAnalysis
  File "/home/titof/anaconda3/envs/MICA/lib/python3.8/site-packages/insightface/__init__.py", line 18, in <module>
    from . import app
  File "/home/titof/anaconda3/envs/MICA/lib/python3.8/site-packages/insightface/app/__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "/home/titof/anaconda3/envs/MICA/lib/python3.8/site-packages/insightface/app/mask_renderer.py", line 8, in <module>
    from ..thirdparty import face3d
  File "/home/titof/anaconda3/envs/MICA/lib/python3.8/site-packages/insightface/thirdparty/face3d/__init__.py", line 3, in <module>
    from . import mesh
  File "/home/titof/anaconda3/envs/MICA/lib/python3.8/site-packages/insightface/thirdparty/face3d/mesh/__init__.py", line 9, in <module>
    from .cython import mesh_core_cython
  File "insightface/thirdparty/face3d/mesh/cython/mesh_core_cython.pyx", line 1, in init insightface.thirdparty.face3d.mesh.cython.mesh_core_cython
**ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject**

Could you help me, thk

**Comment by Zielon** [comment]
The conda env is updated now. Maybe you could try to reinstall it.

**Comment by thornade05** [comment]
Great, install complete, no issue , thk
