### ISSUE TITLE
_pickle.UnpicklingError: the STRING opcode argument must be quoted

### ISSUE THREAD

**Issue by emlcpfx** [Zielon/MICA#51]
I'm on Windows 11, Ubuntu on WSL. I installed using the shell script, and then manually downloaded and placed the buffalo and antelope zip files.

ERROR MESSAGE

(MICA) eric@CPFX02:/mnt/c/Users/Eric/Documents/ML/MICA$ python demo.py
Traceback (most recent call last):
File "/mnt/c/Users/Eric/Documents/ML/MICA/demo.py", line 156, in
main(cfg, args)
File "/mnt/c/Users/Eric/Documents/ML/MICA/demo.py", line 109, in main
mica = util.find_model_using_name(model_dir='micalib.models', model_name=cfg.model.name)(cfg, device)
File "/mnt/c/Users/Eric/Documents/ML/MICA/micalib/models/mica.py", line 35, in init
super(MICA, self).init(config, device, tag)
File "/mnt/c/Users/Eric/Documents/ML/MICA/micalib/base_model.py", line 40, in init
self.masking = Masking(config)
File "/mnt/c/Users/Eric/Documents/ML/MICA/utils/masking.py", line 47, in init
ss = pickle.load(f, encoding="latin1")
_pickle.UnpicklingError: the STRING opcode argument must be quoted

**Comment by leronjulian** [comment]
How did you fix this issue? @emlcpfx

**Comment by emlcpfx** [comment]
I didn't! :(

**Comment by leronjulian** [comment]
Figured it out. This is the reason https://github.com/udacity/ud120-projects/issues/181#issuecomment-411524032
