### ISSUE TITLE
CUDA 11 support / RTX30x0?

### ISSUE THREAD

**Issue by yosun** [Zielon/MICA#55]
Traceback (most recent call last):
  File "demo.py", line 156, in <module>
    main(cfg, args)
  File "demo.py", line 124, in main
    codedict = mica.encode(images, arcface)
  File "/home/yc/testing3dai/mica/MICA/micalib/models/mica.py", line 76, in encode
    codedict['arcface'] = F.normalize(self.arcface(arcface_imgs))
  File "/home/yc/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yc/testing3dai/mica/MICA/models/arcface.py", line 179, in forward
    x = self.forward_arcface(images)
  File "/home/yc/testing3dai/mica/MICA/models/arcface.py", line 188, in forward_arcface
    x = self.prelu(x)
  File "/home/yc/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yc/anaconda3/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 1104, in forward
    return F.prelu(input, self.weight)
  File "/home/yc/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 1499, in prelu
    return torch.prelu(input, weight)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by Zielon** [comment]
I have ran MICA on RTX3090 w/o problems. Not sure what is the issuse in your case.
