### ISSUE TITLE
Code Problem about demo.py

### ISSUE THREAD

**Issue by VictoryLoveJessica** [Zielon/MICA#8]
Thanks for your great work!
I met this error when I tried to run demo.py:
Traceback (most recent call last):
  File "demo.py", line 149, in <module>
    main(cfg, args)
  File "demo.py", line 126, in main
    rendering = mica.render.render_mesh(mesh[None])
  File "/cto_studio/vistring/zhangtianke_code/MICA/micalib/renderer.py", line 69, in render_mesh
    rendering = self.renderer(meshes).permute(0, 3, 1, 2)
  File "/home/anaconda3/envs/MICA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/MICA/lib/python3.8/site-packages/pytorch3d/renderer/mesh/renderer.py", line 60, in forward
    images = self.shader(fragments, meshes_world, **kwargs)
  File "/home/anaconda3/envs/MICA/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/MICA/lib/python3.8/site-packages/pytorch3d/renderer/mesh/shader.py", line 125, in forward
    colors = phong_shading(
  File "/home/anaconda3/envs/MICA/lib/python3.8/site-packages/pytorch3d/renderer/mesh/shading.py", line 90, in phong_shading
    ambient, diffuse, specular = _apply_lighting(
  File "/home/anaconda3/envs/MICA/lib/python3.8/site-packages/pytorch3d/renderer/mesh/shading.py", line 36, in _apply_lighting
    camera_position=cameras.get_camera_center(),
  File "/home/anaconda3/envs/MICA/lib/python3.8/site-packages/pytorch3d/renderer/cameras.py", line 179, in get_camera_center
    P = w2v_trans.inverse().get_matrix()
  File "/home/anaconda3/envs/MICA/lib/python3.8/site-packages/pytorch3d/transforms/transform3d.py", line 277, in inverse
    i_matrix = self._get_matrix_inverse()
  File "/home/anaconda3/envs/MICA/lib/python3.8/site-packages/pytorch3d/transforms/transform3d.py", line 247, in _get_matrix_inverse
    return torch.inverse(self._matrix)
torch._C._LinAlgError: cusolver error: CUSOLVER_STATUS_EXECUTION_FAILED, when calling `cusolverDnSgetrf( handle, m, n, dA, ldda, static_cast<float*>(dataPtr.get()), ipiv, info)`. This error may appear if the input matrix contains NaN.

**Comment by i-amgeek** [comment]
Hi @VictoryLoveJessica , how did you solve this? I am getting same issue.

**Comment by VictoryLoveJessica** [comment]
It means that your environment has some problems, which might be a conflict between installing insightface and pytorch3d（my sitution).
