### ISSUE TITLE
Hello, I am using M1 Macbook pro. 

### ISSUE THREAD

**Issue by alnrg2arg** [Zielon/MICA#9]
Mac cannot use the CUDA as long as I know. I encountered the error that "Torch not compiled with CUDA enabled", while running the demo.py. Below is the message I received. 

/Users/user/miniforge3/lib/python3.9/site-packages/pytorch3d/renderer/opengl/__init__.py:16: UserWarning: Can't import EGL, not importing MeshRasterizerOpenGL. This might happen if your Python application imported OpenGL with a non-EGL backend before importing PyTorch3D, or if you don't have pyopengl installed as part of your Python distribution.
  warnings.warn(
2022-07-29 10:55:41.258 | INFO     | models.flame:__init__:54 - [FLAME] creating the FLAME Decoder
2022-07-29 10:55:42.083 | INFO     | models.flame:__init__:54 - [FLAME] creating the FLAME Decoder
2022-07-29 10:55:42.109 | INFO     | micalib.models.mica:load_model:59 - [MICA] Checkpoint not available starting from scratch!
/Users/user/miniforge3/lib/python3.9/site-packages/pytorch3d/io/obj_io.py:531: UserWarning: No mtl file provided
  warnings.warn("No mtl file provided")
Traceback (most recent call last):
  File "/Users/user/MICA/demo.py", line 149, in <module>
    main(cfg, args)
  File "/Users/user/MICA/demo.py", line 105, in main
    mica = util.find_model_using_name(model_dir='micalib.models', model_name=cfg.model.name)(cfg, device)
  File "/Users/user/MICA/micalib/models/mica.py", line 37, in __init__
    self.initialize()
  File "/Users/user/MICA/micalib/base_model.py", line 48, in initialize
    self.setup_renderer(self.cfg.model)
  File "/Users/user/MICA/micalib/base_model.py", line 91, in setup_renderer
    self.render = MeshShapeRenderer(obj_filename=model_cfg.topology_path)
  File "/Users/user/MICA/micalib/renderer.py", line 33, in __init__
    faces = faces.verts_idx[None, ...].cuda()
  File "/Users/user/miniforge3/lib/python3.9/site-packages/torch/cuda/__init__.py", line 211, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

Could you please tell me how I can deal with or fix the error?

**Comment by Zielon** [comment]
You can try to change the device in the code from `cuda` to use `cpu`. I haven't written it in a generic way. Maybe soon I will add a patch so that users can specify it in the config.
